### ISSUE TITLE
Announcement Feature: Adding Support for Guild Member Property and Handling Discord-Bot permissions

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/api#275]
### **Description:**
The primary goals are to add support for the guild member property and to handle the access rights of the Discord bot efficiently. This includes developing a new API for the Announcement feature, modifying the /platform/:platformId/properties endpoint, and ensuring proper permission management.

### **Tasks to Implement:**

 

- [x]  Create and integrate an API to get the required permissions for the discord-bot
- [x]  Modify the /platform/:platformId/properties Endpoint to include a new field in the response for channel properties, indicating the Discord bot's required permissions.
- [x]  Extend the /platform/:platformId/properties to support the guild member property.
- [x]   Add a server level permission for each module.
