### ISSUE TITLE
MediaWiki Platform + MediaWiki settings for Hivemind + Enums For names

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/api#357]
### **Documentaions**
-   [Platform - MediaWiki API](https://www.notion.so/rndadocs/Platform-MediaWiki-API-05239ba9f12c4cc2a439eea66d75e634)
-   [Hivemind Module - MediaWiki Validator](https://www.notion.so/rndadocs/Hivemind-Module-MediaWiki-Validator-37dbf7c40251440bb8869b147e578f6e)

### **Tasks**
- [x] Add MediaWiki OAuth2 
- [x] add MediaWiki setting for hivemind module
- [x] use enums for platform and module names
