### ISSUE TITLE
Discourse Platform + Violation Detection Module

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/api#390]
### **Tasks**

- [x]  Discourse Platform Creation
- [x]   Violation Detection Module Creation
- [x] Discourse  Config for Violation Detection Module 
- [x] airflow analyzer API

### References:
-   [API - Violation Detection Module + Discourse Validatior](https://www.notion.so/rndadocs/API-Violation-Detection-Module-Discourse-Validatior-ae36449bc80a499e9bc08e2476ad0a33)
-   [Platform - Discourse API](https://www.notion.so/rndadocs/Platform-Discourse-API-337cd39be7fb491c906bf1bbf88ecaff)
