### ISSUE TITLE
Telegram Verification

### ISSUE THREAD

**Issue by Behzad-rabiei** [TogetherCrew/api#418]
### **Description**
Implement and update API endpoints and logic to support generating, validating, and expiring Telegram verification tokens, as well as updating endpoints related to platforms to support Telegram.

### **Tasks**
- [x] Implement POST /auth/generate-token endpoint to create a Telegram verification token linked to a given community ID
- [x] Store tokens with expiration timestamps 
- [x] Update the Platform APIs to support telegram
- [x] Update Docs
