### ISSUE TITLE
RabbitMQ: Channel Selection & Period - Workflow API Endpoint (Server)

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/api#88]
In reference to:
https://www.notion.so/channel-selection-connected-to-data-shown-in-line-graphs-and-heatmap-c3d454ad0ea140649728ea0b62a1c4d8?pvs=4

This should be implemented as per the following diagram:
https://miro.com/app/board/uXjVMPYA244=/?share_link_id=123845624136

**Tasks**
- [ ] Should have workflow endpoint with `uuid` as param
- [ ] Should query the workflow in the db
- [ ] Should return the workflow to the requestor
